### ISSUE TITLE
failed to run demo

### ISSUE THREAD

**Issue by wyfSunflower** [gravi-toni/subpixel-edges#7]
Hi,could anyone can help me? I run demo failed,demo script is:
`import cv2
import matplotlib.pyplot as plt

from subpixel_edges import subpixel_edges

# (optional) 
# help(subpixel_edges) 

img = cv2.imread("lena.png")
img_gray = (cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)).astype(float)
edges = subpixel_edges(img_gray, 25, 0, 2)

plt.imshow(img)
plt.quiver(edges.x, edges.y, edges.nx, -edges.ny, scale=40)
plt.show()`

it throw out such error:
C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\subpixel_edges\final_detector_iter0.py:22: FutureWarning: In the future `np.bool` will be 
defined as the corresponding NumPy scalar.
  Ey = np.zeros((rows, cols), dtype=np.bool)
Traceback (most recent call last):
  File "d:/lib/demo.py", line 11, in <module>
    edges = subpixel_edges(img_gray, 25, 0, 2)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\subpixel_edges\__init__.py", line 59, in subpixel_edges
    return main_iter0(img, threshold, iters, order)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\subpixel_edges\final_detector_iter0.py", line 22, in main_iter0
    Ey = np.zeros((rows, cols), dtype=np.bool)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` 
here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

thanks!

**Comment by wyfSunflower** [comment]
change numpy.bool to numpy.bool_
